### PR TITLE
features/x-lablel-i18n

### PR DESCRIPTION
**Pull request by rkorzeniec**
Add i18n to X-Label component. Defaults to English.
before:
Screenshot 2019-08-19 at 11 41 16

after:
Screenshot 2019-08-19 at 13 05 28

### CODE REVIEW

**Comment by rkorzeniec** [comment]
@nathanstitt I fixed the merge conflicts 😉

**Comment by nathanstitt** [comment]
Thanks so much!

**Comment by nathanstitt** [comment]
this was just released as version 2.5.0.  Thanks again for the contribution!

**Comment by rkorzeniec** [comment]
@nathanstitt you're welcome

**Pull request merged**
