### PR TITLE
Feature/add possibility to start week on sunday or monday

### PR DESCRIPTION
**Pull request by itsnorbertkalacska**
## Description
Until this point there was no option to set which day the week should start on. Because of the `locale` prop to `XLabels` component was updated however the `Layout` wasn't so the labels and the days with the events didn't match. This PR fixes this bug and also adds the opportunity leave the starting day to the `locale` prop or set it to Sunday or Monday no matter the localization.

**Types of changes**
What types of changes does your code introduce? Only leave matching option:
- New feature (non-breaking change which adds functionality)
- Bugfix (non-breaking change which fixes an issue)

**Related links**
https://momentjs.com/docs/#/get-set/day-of-year/
https://momentjs.com/docs/#/get-set/iso-weekday/

#### Added
- `weekStartsOn` prop to `Dayz`
- `weekStartsOn` prop to `XLabels`
- tests for `calculateRange`'s new cases

#### Changed
- README
- `calculateRange` function in `Layout`
- `days` function in `XLabels`
- updated snapshots

### CODE REVIEW

**Comment by itsnorbertkalacska** [comment]
@nathanstitt Hey! 

Thank you for the quick response on other PR! It helps us out a lot!

We need this feature for our project. Do you mind adding this functionality to your component?

We'd really appreciate if you could take a look at this!

Thank you in advance!

Cheers

**Comment by nathanstitt** [comment]
@itsnorbertkalacska Thanks so much for the reminder. I saw this when it came in and liked it but put off a proper look until later and then promptly forgot about it 😭    

I think the code looks excellent, I'll merge and release a new version shortly

**Comment by nathanstitt** [comment]
Was released as `v2.8.0`

**Comment by itsnorbertkalacska** [comment]
@nathanstitt Thank you so much! Appreciate it! 🙏🏻

It's a pleasure to work with you. For real.

**Pull request merged**
